services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONVEX_URL=https://wry-bobcat-240.convex.cloud
      - OLIST_API_KEY=328caf8acea774903bc8d88fbdab51eb509420ee77e443e3aac7f1a6396e216f
      - CRON_CUSTOMER_DISCOVERY=0 2 * * *
      - CRON_MARGIN_CALCULATION=15 23 * * *
      - TZ=America/Sao_Paulo
      - CRON_RUN_ON_STARTUP=true
    networks:
      - new-clean-api-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - new-clean-api-network

networks:
  new-clean-api-network:
    driver: bridge

volumes:
  redis-data:
