services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONVEX_URL=${CONVEX_URL}
      - NEW_CLEAN_API_KEY=${OLIST_API_KEY}
    networks:
      - new-clean-api-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - new-clean-api-network

networks:
  new-clean-api-network:
    driver: bridge

volumes:
  redis-data:
